# Configuration for the AI Email Generator
gemini:
  model: "gemini-1.5-flash"  # or "gemini-1.5-pro" for more advanced responses
  api_key: "GEMINI_API_KEY"  # Set this or use GEMINI_API_KEY environment variable
  temperature: 0.7
  max_output_tokens: 1000
  top_p: 0.9
  top_k: 40

api:
  host: "0.0.0.0"
  port: 5000
  debug: false

logging:
  level: "INFO"
  file: "logs/email_generator.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5
